# Generated by Django 5.0.1 on 2024-01-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
