# Generated by Django 5.0.1 on 2024-01-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
