# Generated by Django 5.0.1 on 2024-01-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_minitest_questions_alter_minitest_test_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='test',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
