# Generated by Django 5.0.1 on 2024-01-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_topic_chapter_remove_question_chapter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minitest',
            name='chapter',
            field=models.CharField(default='Do Your Best', max_length=100),
        ),
    ]
