# Generated by Django 5.0.1 on 2024-01-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_minitest_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='quiz_data',
            field=models.JSONField(default=list),
        ),
    ]
